# 修正X、Y轴的最大值；若未设置则使用设备的报告描述符中提供的最大值
# TIPS：可以用evtest观察原始的事件设备的X轴、Y轴最大值（注意两个坐标轴需要调换）
# 注意：这两个字段不支持热更新
xMaxValue = 16123
yMaxValue = 26151

# 将X、Y轴的值映射到指定的比例区间内，从而实现映射到显示器的某个区域的效果；若未设置，则映射到显示器的整个区域
# 下面的例子将绘图板映射到了显示器的靠左中间区域
xMap = [0, 0.5]
yMap = [0.25, 0.75]

[[keymap]]
# 默认按键映射方案
button0 = "ctrl+shift+z" # krita: redo
button1 = "ctrl+z" # krita: undo
button2 = "p" # krita: color picker
button3 = "[" # krita: decrease brush size
button4 = "]" # krita: increase brush size
button5 = "b" # krita: brush
button6 = "e" # krita: eraser
button7 = "x" # krita: switch color
ring0 = "-" # krita: zoom out
ring1 = "=" # krita: zoom in
ringButton = "switchSchema"

[[keymap]]
# 候选按键映射方案
ring0 = "ctrl+[" # krita: rotate counter-clockwise
ring1 = "ctrl+]" # krita: rotate clockwise
# 未配置的键默认将使用前一个方案的按键映射
# button0 = "fallback"
# button1 = "fallback"
# button2 = "fallback"
# button3 = "fallback"
# button4 = "fallback"
# button5 = "fallback"
# button6 = "fallback"
# button7 = "fallback"
# ringBbutton = "fallback"
